// Golden parity suite: replays every case in fixtures/r-sna-2.8/parity.json
// (generated by scripts/generate-r-snapshots.R against R sna 2.8) through the
// TypeScript port and compares numerically.
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { describe, expect, it } from "vitest";

import {
  betweenness,
  bonpow,
  centralization,
  closeness,
  componentDist,
  components,
  connectedness,
  degree,
  dyadCensus,
  efficiency,
  evcent,
  flowbet,
  gden,
  geodist,
  gilschmidt,
  graphcent,
  grecip,
  gtrans,
  hierarchy,
  infocent,
  isolates,
  kcores,
  loadcent,
  lubness,
  mutuality,
  nties,
  prestige,
  reachability,
  stresscent,
  symmetrize,
  triadCensus,
  type CentralizationMeasureName,
} from "../../src/index";

type Tagged = number | "NA" | "NaN" | "Inf" | "-Inf";
type Value = Tagged | Value[] | { [key: string]: Value };

interface FixtureCase {
  readonly id: string;
  readonly fn: string;
  readonly graph: string;
  readonly options: Record<string, unknown>;
  readonly expected: Value;
}

interface Fixture {
  readonly provenance: { readonly snaVersion: string; readonly rVersion: string };
  readonly graphs: Record<string, Tagged[][]>;
  readonly cases: FixtureCase[];
}

const fixture: Fixture = JSON.parse(readFileSync(join(__dirname, "../../fixtures/r-sna-2.8/parity.json"), "utf8")) as Fixture;

function decodeNumber(value: Tagged): number {
  if (value === "NA" || value === "NaN") return Number.NaN;
  if (value === "Inf") return Number.POSITIVE_INFINITY;
  if (value === "-Inf") return Number.NEGATIVE_INFINITY;
  return value;
}

function decode(value: Value): unknown {
  if (Array.isArray(value)) return value.map(decode);
  if (typeof value === "object" && value !== null) return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, decode(v)]));
  return decodeNumber(value);
}

const graphs = Object.fromEntries(Object.entries(fixture.graphs).map(([name, m]) => [name, m.map((row) => row.map(decodeNumber))]));

// Per-function relative tolerance; the default suits exact algorithms, the
// looser entries cover iterative/linear-algebra paths.
const TOLERANCE: Record<string, number> = { default: 1e-9, evcent: 1e-6, bonpow: 1e-6, infocent: 1e-6 };

function expectClose(actual: unknown, expected: unknown, tolerance: number, path: string): void {
  // R cannot distinguish a scalar from a length-1 vector, so fixture scalars
  // arrive as one-element arrays; unwrap when the JS side returned a number.
  if (Array.isArray(expected) && expected.length === 1 && typeof actual === "number") {
    expected = expected[0];
  }
  if (typeof expected === "number") {
    expect.soft(typeof actual, `${path}: type`).toBe("number");
    const a = actual as number;
    if (Number.isNaN(expected)) expect.soft(Number.isNaN(a), `${path}: expected NaN, got ${a}`).toBe(true);
    else if (!Number.isFinite(expected)) expect.soft(a, path).toBe(expected);
    else {
      const pass = Math.abs(a - expected) <= tolerance * Math.max(1, Math.abs(expected));
      expect.soft(pass, `${path}: |${a} - ${expected}| exceeds tolerance`).toBe(true);
    }
    return;
  }
  if (Array.isArray(expected)) {
    expect.soft(Array.isArray(actual), `${path}: expected array`).toBe(true);
    expect.soft((actual as unknown[]).length, `${path}: length`).toBe(expected.length);
    expected.forEach((entry, index) => expectClose((actual as unknown[])[index], entry, tolerance, `${path}[${index}]`));
    return;
  }
  if (typeof expected === "object" && expected !== null) {
    for (const [key, entry] of Object.entries(expected)) {
      expectClose((actual as Record<string, unknown>)[key], entry, tolerance, `${path}.${key}`);
    }
    return;
  }
  expect.soft(actual, path).toEqual(expected);
}

type Runner = (matrix: number[][], options: Record<string, never>) => unknown;

const RUNNERS: Record<string, Runner> = {
  degree: (m, o) => degree(m, o),
  gden: (m, o) => gden(m, o),
  nties: (m, o) => nties(m, o),
  geodist: (m, o) => {
    const result = geodist(m, o);
    return { gdist: result.distances, counts: result.counts };
  },
  betweenness: (m, o) => betweenness(m, o),
  closeness: (m, o) => closeness(m, o),
  stresscent: (m, o) => stresscent(m, o),
  loadcent: (m, o) => loadcent(m, o),
  graphcent: (m, o) => graphcent(m, o),
  evcent: (m, o) => evcent(m, o),
  bonpow: (m, o) => bonpow(m, o),
  infocent: (m, o) => infocent(m, o),
  prestige: (m, o) => prestige(m, o),
  gilschmidt: (m, o) => gilschmidt(m, o),
  flowbet: (m, o) => flowbet(m, o),
  dyadCensus: (m, o) => {
    const result = dyadCensus(m, o);
    return { mut: result.mutual, asym: result.asymmetric, null: result.nullDyads };
  },
  triadCensus: (m, o) => triadCensus(m, o),
  grecip: (m, o) => grecip(m, o),
  mutuality: (m, o) => mutuality(m, o),
  gtrans: (m, o) => gtrans(m, o),
  connectedness: (m, o) => connectedness(m, o),
  efficiency: (m, o) => efficiency(m, o),
  lubness: (m, o) => lubness(m, o),
  hierarchy: (m, o) => hierarchy(m, o),
  componentDist: (m, o) => {
    const result = componentDist(m, o);
    return {
      csize_sorted: [...result.csize].sort((a, b) => b - a),
      count: result.csize.length,
      cdist: result.cdist,
    };
  },
  components: (m, o) => components(m, o).count,
  reachability: (m, o) => reachability(m, o),
  isolates: (m, o) => isolates(m, o),
  kcores: (m, o) => kcores(m, o),
  symmetrize: (m, o) => symmetrize(m, o),
  centralization: (m, o) => {
    const { measure, ...rest } = o as { measure: CentralizationMeasureName } & Record<string, never>;
    return centralization(m, measure, rest);
  },
};

describe(`R sna ${fixture.provenance.snaVersion} golden parity (${fixture.cases.length} cases)`, () => {
  const byFn = new Map<string, FixtureCase[]>();
  for (const parityCase of fixture.cases) {
    const list = byFn.get(parityCase.fn) ?? [];
    list.push(parityCase);
    byFn.set(parityCase.fn, list);
  }

  for (const [fn, fnCases] of byFn) {
    describe(fn, () => {
      const runner = RUNNERS[fn];
      it.each(fnCases.map((c) => [c.id, c] as const))("%s", (_id, parityCase) => {
        expect(runner, `no runner registered for fixture fn "${fn}"`).toBeDefined();
        const matrix = graphs[parityCase.graph];
        expect(matrix, `unknown corpus graph "${parityCase.graph}"`).toBeDefined();
        const actual = runner!(matrix!, parityCase.options as Record<string, never>);
        const expected = decode(parityCase.expected);
        expectClose(actual, expected, TOLERANCE[fn] ?? TOLERANCE.default!, parityCase.id);
      });
    });
  }
});
