// R-name compatibility table for the exported API.
import { betweenness } from "../algorithms/betweenness";
import { bonpow } from "../algorithms/bonpow";
import { centralization } from "../algorithms/centralization";
import { closeness } from "../algorithms/closeness";
import { components, isConnected } from "../algorithms/components";
import { componentDist, componentLargest, componentSizeByVertex, neighborhood, reachability } from "../algorithms/connectivity";
import {
  addIsolates,
  asEdgelistSna,
  asSociomatrixSna,
  diagRemove,
  egoExtract,
  event2dichot,
  gt,
  gvectorize,
  intervalGraph,
  isEdgelistSna,
  lowerTriRemove,
  makeStochastic,
  sr2css,
  stackcount,
  symmetrize,
  upperTriRemove,
} from "../algorithms/dataprep";
import { degree } from "../algorithms/degree";
import { evcent } from "../algorithms/evcent";
import { flowbet } from "../algorithms/flowbet";
import { gden, nties } from "../algorithms/density";
import { readDot, readNos, writeDl, writeNos } from "../algorithms/fileio";
import { geodist } from "../algorithms/geodist";
import { gilschmidt } from "../algorithms/gilschmidt";
import { graphcent } from "../algorithms/graphcent";
import { centralgraph, gclustBoxstats, gclustCentralgraph, gcor, gcov, gscor, gscov, hdist, sdmat, structdist } from "../algorithms/graphComparison";
import { cugTest, cugtest, qaptest } from "../algorithms/graphTests";
import { connectedness, dyadCensus, efficiency, grecip, gtrans, hierarchy, lubness, mutuality } from "../algorithms/graphStatistics";
import { infocent } from "../algorithms/infocent";
import { isolates, isIsolate } from "../algorithms/isolates";
import { loadcent } from "../algorithms/loadcent";
import {
  bbnam,
  bbnamActor,
  bbnamBf,
  bbnamFixed,
  bbnamJntlik,
  bbnamJntlikSlice,
  bbnamPooled,
  bbnamProbtie,
  bn,
  bnDyadStats,
  bnNlplDyad,
  bnNlplEdge,
  bnNlplTriad,
  bnNltl,
  bnPtriad,
  bnTriadStats,
  brokerage,
  coefBn,
  coefLnam,
  consensus,
  evalEdgeperturbation,
  lnam,
  nacf,
  netcancor,
  netlm,
  netlogit,
  npostpred,
  potscaleredMcmc,
  pstar,
  seLnam,
} from "../algorithms/models";
import { gapply, gliop, graphComposition, logMean, logSub, logSum } from "../algorithms/operators";
import { onAttach, onLoad } from "./packageHooks";
import { labOptimize, labOptimizeAnneal, labOptimizeExhaustive, labOptimizeGumbel, labOptimizeHillclimb, labOptimizeMc, numperm, rmperm, rperm } from "../algorithms/permutation";
import { prestige } from "../algorithms/prestige";
import { rewireUd, rewireWs, rgbn, rgnm, rgnmix, rgraph, rguman, rgws } from "../algorithms/randomGraph";
import { blockmodel, blockmodelExpand, equivClust, redist, sedist } from "../algorithms/roles";
import {
  bicomponentDist,
  cliqueCensus,
  cutpoints,
  kcores,
  kcycleCensus,
  kpathCensus,
  maxflow,
  simmelian,
  structureStatistics,
} from "../algorithms/structural";
import { stresscent } from "../algorithms/stresscent";
import { triadCensus, triadClassify } from "../algorithms/triads";
import * as display from "../display";

export const snaR = {
  ...display,
  betweenness,
  bonpow,
  addIsolates,
  asEdgelistSna,
  asSociomatrixSna,
  bicomponentDist,
  blockmodel,
  blockmodelExpand,
  centralization,
  centralgraph,
  closeness,
  cliqueCensus,
  componentDist,
  componentLargest,
  componentSizeByVertex,
  components,
  connectedness,
  cutpoints,
  cugTest,
  cugtest,
  degree,
  dyadCensus,
  efficiency,
  equivClust,
  evcent,
  flowbet,
  gden,
  gapply,
  gclustBoxstats,
  gclustCentralgraph,
  gcor,
  gcov,
  geodist,
  gilschmidt,
  gliop,
  grecip,
  graphcent,
  graphComposition,
  gscor,
  gscov,
  gtrans,
  hdist,
  diagRemove,
  egoExtract,
  event2dichot,
  gt,
  gvectorize,
  hierarchy,
  infocent,
  isolates,
  isIsolate,
  kcores,
  kcycleCensus,
  kpathCensus,
  intervalGraph,
  isEdgelistSna,
  lnam,
  logMean,
  logSub,
  logSum,
  nacf,
  loadcent,
  lubness,
  maxflow,
  neighborhood,
  netcancor,
  netlm,
  netlogit,
  nties,
  numperm,
  onAttach,
  onLoad,
  labOptimize,
  labOptimizeAnneal,
  labOptimizeExhaustive,
  labOptimizeGumbel,
  labOptimizeHillclimb,
  labOptimizeMc,
  prestige,
  qaptest,
  reachability,
  redist,
  rewireUd,
  rewireWs,
  rgbn,
  rgnm,
  rgnmix,
  rgraph,
  rguman,
  rgws,
  readDot,
  readNos,
  writeDl,
  writeNos,
  rmperm,
  rperm,
  sdmat,
  sedist,
  simmelian,
  stresscent,
  structdist,
  structureStatistics,
  mutuality,
  pstar,
  bbnam,
  bbnamActor,
  bbnamBf,
  bbnamFixed,
  bbnamJntlik,
  bbnamJntlikSlice,
  bbnamPooled,
  bbnamProbtie,
  brokerage,
  bn,
  bnDyadStats,
  bnNlplDyad,
  bnNlplEdge,
  bnNlplTriad,
  bnNltl,
  bnPtriad,
  coefBn,
  coefLnam,
  consensus,
  evalEdgeperturbation,
  npostpred,
  potscaleredMcmc,
  seLnam,
  makeStochastic,
  sr2css,
  stackcount,
  lowerTriRemove,
  symmetrize,
  triadCensus,
  triadClassify,
  upperTriRemove,
  "add.isolates": addIsolates,
  "as.edgelist.sna": asEdgelistSna,
  "as.sociomatrix.sna": asSociomatrixSna,
  "bicomponent.dist": bicomponentDist,
  "blockmodel.expand": blockmodelExpand,
  "clique.census": cliqueCensus,
  "component.dist": componentDist,
  "component.largest": componentLargest,
  "component.size.byvertex": componentSizeByVertex,
  "cug.test": cugTest,
  "diag.remove": diagRemove,
  "dyad.census": dyadCensus,
  "ego.extract": egoExtract,
  "eval.edgeperturbation": evalEdgeperturbation,
  "equiv.clust": equivClust,
  "gdist.plotdiff": display.gdistPlotdiff,
  "gdist.plotstats": display.gdistPlotstats,
  "gclust.boxstats": gclustBoxstats,
  "gclust.centralgraph": gclustCentralgraph,
  "is.connected": isConnected,
  "is.edgelist.sna": isEdgelistSna,
  "is.isolate": isIsolate,
  "interval.graph": intervalGraph,
  "kcycle.census": kcycleCensus,
  "kpath.census": kpathCensus,
  "lower.tri.remove": lowerTriRemove,
  "%c%.matrix": graphComposition,
  "bbnam.actor": bbnamActor,
  "bbnam.bf": bbnamBf,
  "bbnam.fixed": bbnamFixed,
  "bbnam.jntlik": bbnamJntlik,
  "bbnam.jntlik.slice": bbnamJntlikSlice,
  "bbnam.pooled": bbnamPooled,
  "bbnam.probtie": bbnamProbtie,
  "bn.dyadstats": bnDyadStats,
  "bn.nlpl.dyad": bnNlplDyad,
  "bn.nlpl.edge": bnNlplEdge,
  "bn.nlpl.triad": bnNlplTriad,
  "bn.nltl": bnNltl,
  "bn.ptriad": bnPtriad,
  "bn.triadstats": bnTriadStats,
  "coef.bn": coefBn,
  "coef.lnam": coefLnam,
  "lab.optimize": labOptimize,
  "lab.optimize.anneal": labOptimizeAnneal,
  "lab.optimize.exhaustive": labOptimizeExhaustive,
  "lab.optimize.gumbel": labOptimizeGumbel,
  "lab.optimize.hillclimb": labOptimizeHillclimb,
  "lab.optimize.mc": labOptimizeMc,
  "potscalered.mcmc": potscaleredMcmc,
  "make.stochastic": makeStochastic,
  "read.dot": readDot,
  "read.nos": readNos,
  "rewire.ud": rewireUd,
  "rewire.ws": rewireWs,
  "structure.statistics": structureStatistics,
  "triad.census": triadCensus,
  "triad.classify": triadClassify,
  "upper.tri.remove": upperTriRemove,
  "write.dl": writeDl,
  "write.nos": writeNos,
  "se.lnam": seLnam,
  "summary.qaptest": display.summaryQaptest,
  "summary.cugtest": display.summaryCugtest,
  "print.qaptest": display.printQaptest,
  "print.cugtest": display.printCugtest,
  "print.cug.test": display.printCugTest,
  "print.summary.qaptest": display.printSummaryQaptest,
  "print.summary.cugtest": display.printSummaryCugtest,
  "plot.qaptest": display.plotQaptest,
  "plot.cugtest": display.plotCugtest,
  "plot.cug.test": display.plotCugTest,
  ".onLoad": onLoad,
  ".onAttach": onAttach,
  "summary.netlm": display.summaryNetlm,
  "summary.netlogit": display.summaryNetlogit,
  "summary.pstar": display.summaryPstar,
  "print.netlm": display.printNetlm,
  "print.netlogit": display.printNetlogit,
  "print.pstar": display.printPstar,
  "print.summary.netlm": display.printSummaryNetlm,
  "print.summary.netlogit": display.printSummaryNetlogit,
  "plot.lnam": display.plotLnam,
  "summary.lnam": display.summaryLnam,
  "summary.brokerage": display.summaryBrokerage,
  "summary.netcancor": display.summaryNetcancor,
  "print.lnam": display.printLnam,
  "print.summary.brokerage": display.printSummaryBrokerage,
  "print.netcancor": display.printNetcancor,
  "print.summary.netcancor": display.printSummaryNetcancor,
  "print.summary.lnam": display.printSummaryLnam,
  "plot.bn": display.plotBn,
  "summary.bn": display.summaryBn,
  "print.bn": display.printBn,
  "print.summary.bn": display.printSummaryBn,
  "plot.bbnam": display.plotBbnam,
  "plot.bbnam.fixed": display.plotBbnamFixed,
  "plot.bbnam.pooled": display.plotBbnamPooled,
  "plot.bbnam.actor": display.plotBbnamActor,
  "summary.bbnam": display.summaryBbnam,
  "summary.bbnam.fixed": display.summaryBbnamFixed,
  "summary.bbnam.pooled": display.summaryBbnamPooled,
  "summary.bbnam.actor": display.summaryBbnamActor,
  "print.bbnam": display.printBbnam,
  "print.bbnam.fixed": display.printBbnamFixed,
  "print.bbnam.pooled": display.printBbnamPooled,
  "print.bbnam.actor": display.printBbnamActor,
  "print.summary.bbnam": display.printSummaryBbnam,
  "print.summary.bbnam.fixed": display.printSummaryBbnamFixed,
  "print.summary.bbnam.pooled": display.printSummaryBbnamPooled,
  "print.summary.bbnam.actor": display.printSummaryBbnamActor,
  "summary.bayes.factor": display.summaryBayesFactor,
  "print.bayes.factor": display.printBayesFactor,
  "print.summary.bayes.factor": display.printSummaryBayesFactor,
  "summary.blockmodel": display.summaryBlockmodel,
  "print.blockmodel": display.printBlockmodel,
  "print.equiv.clust": display.printEquivClust,
  "print.summary.blockmodel": display.printSummaryBlockmodel,
  "plot.blockmodel": display.plotBlockmodel,
  "plot.equiv.clust": display.plotEquivClust,
} as const;
